export const QUERY_KEYS = {
    CITIES: 'cities',
    CURRENT_USER: 'current-user',
    IS_ADMIN: 'is-admin',
    SEARCH_CARWASHES: 'carwashes',
    CURRENT_CARWASH: 'current-carwash',
    ADMIN_CARWASHES: 'admin-carwashes',
    ADMIN_CARWASH: 'admin-carwash',
    SEARCH_FILTERS: 'filters',
    USER_VEHICLES: 'vehicles',
    GROUPED: 'grouped',
    FLAT: 'flat',
    VEHICLE_TYPES: 'vehicle-types',
    SCRIPTS: 'scripts',
    SCRIPT_SERVICES: 'script_services',
    SCRIPT_SERVICE_PARAMS: 'script_service_params',
    SCRIPT_VEHICLE_TYPES: 'script_vehicle_types',
    CAR_WASH_BOXES: 'car_wash_boxes',
    SCRIPT_BOXES: 'script_boxes',
    SCRIPT_WORKERS: 'script_workers',
    CAR_WASH_WORKERS: 'car_wash_workers',
};
